### ISSUE TITLE
stop the spinner on error

### ISSUE THREAD

**Issue by Aliendreamer** [gpyanev/spacex-launches-demo#5]
Now when error occur you show the modal and backdrop which is ok but  closing the modal leave you on spinner you have to stop it too,as the page stays irresponsive. just stop it and add an message on the page or error page item instead of the launches list.
some thing like .. Pls try again or try later something went wrong.

**Comment by gpyanev** [comment]
I left the spinner because we are already showing the error modal but now it's replaced with an error message.
